---
title: "Modelo de crecimiento logístico y de Gompertz"
subtitle: "Análisis Demográfico"
author: "Jacob Hernández"
date: "2020-09-30"
output: 
  tint::tintHtml:
    anchor_sections: false
    includes:
      in_header: header.html
bibliography: refs.bib
link-citations: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = "svglite")
options(knitr.kable.NA = '')

library(tidyverse)
library(hrbrthemes)
library(ggtext)

theme_set(theme_ipsum_rc())
theme_update(
  plot.background = element_rect(fill = "#FEFEFE", color = NA),
  panel.grid.minor.x = element_blank()
)
```

# Función de ajuste 

```{r}
growth_model <- function(training, date_col = "date", pop_col = "pop", 
                         type = c("log","gmp")){
  
  data <- as.data.frame(training)
  
  nr <- nrow(data)
  n <- nr %/% 3
   
  if (nr %% 3 == 1) {
    data <- data[-1,]
  } else if (nr %% 3  == 2) {
    data <- data[-c(1,nr),]
  }
  
  fd <- data[1, date_col]
  dd <- diff(data[1:2, date_col])
  
  if (type == "log") {
    s <- map_dbl(0:2, ~sum(1/data[1:n + .x*n, pop_col]))
  } else if (type == "gmp") {
    s <- map_dbl(0:2, ~sum(log(data[1:n + .x*n, pop_col])))
  }
  
  c <- ((s[3]-s[2])/(s[2]-s[1]))**(1/n)
  h <- (s[2]-s[1])*(c-1)/(c**n-1)**2
  k <- 1/n*(s[1]-(c**n-1)/(c-1)*h)
  
  if (type == "log") {
    function(date) 1/(k+h*c**((date-fd)/dd))
  } else if (type == "gmp") {
    function(date) exp(k+h*c**((date-fd)/dd))
  }
}
```

# Proyecciones hasta el año 2030

```{r}
data <- tibble(
  t = seq(1950, 2000, 10),
  P = c(8.31,10.39, 12.66, 14.81, 17.17, 19.27)
)

mod1 <- growth_model(data, date_col = "t", pop_col = "P", type = "log")
mod2 <- growth_model(data, date_col = "t", pop_col = "P", type = "gmp")

projections <- data %>% 
  bind_rows(tibble(t = seq(2010, 2030, 10))) %>% 
  mutate(
    .plog = mod1(t), 
    .pgmp = mod2(t) 
  )
```

## Resultados

```{r echo=FALSE, fig.margin = TRUE}
projections %>% 
  ggplot(aes(t, P)) +
    stat_function(fun = mod2, geom = "area", fill = "#F28E2C") +
    stat_function(fun = mod1, geom = "area", fill = "#4E79A7") +
    geom_line() +
    geom_point(shape = 21, fill = "#FFFFFF") +
    expand_limits(y = 0) +
    scale_y_continuous(breaks = seq(5,25,5)) +
    labs(
      title = "Proyecciones de población",
      subtitle = "Modelo <b style='color:#4E79A7;'>logístico</b> y <b style='color:#F28E2C;'>de Gompertz</b>.",
      y = "Millones de habitantes",
      x = "Año"
      ) +
    theme(
      plot.subtitle = element_markdown(),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.y = element_blank()
    )
```

```{r echo=FALSE}
projections %>% 
  set_names("Año", "Población", "M. Logístico", "M. Gompertz") %>% 
  knitr::kable()
```
